"""Round-trip tests against real binary documents (FR-2).

Each fixture is generated by the library that owns the format, so these
exercise genuine files rather than stubs. Skipped when the optional format
libraries are absent -- their absence must degrade coverage, never break the
suite (see pyproject `formats` extra).
"""

from __future__ import annotations

from pathlib import Path

import pytest

from datamanager.extract import text
from datamanager.index.indexer import Indexer
from datamanager.query.search import SearchEngine
from datamanager.scan.scanner import Scanner


def test_docx_paragraphs_and_tables(tmp_path: Path):
    docx = pytest.importorskip("docx")

    path = tmp_path / "lease.docx"
    document = docx.Document()
    document.add_paragraph("Residential Lease Agreement")
    document.add_paragraph("Tenant: Jane Doe")
    table = document.add_table(rows=2, cols=2)
    table.cell(0, 0).text = "Monthly rent"
    table.cell(0, 1).text = "2450.00"
    table.cell(1, 0).text = "Lease ends"
    table.cell(1, 1).text = "2025-08-31"
    document.save(str(path))

    result = text.extract(path)

    assert result.status == "complete"
    assert "Residential Lease Agreement" in result.text
    assert "Monthly rent" in result.text, "table cells must be extracted"
    assert "2450.00" in result.text


def test_xlsx_sheets_and_cells(tmp_path: Path):
    openpyxl = pytest.importorskip("openpyxl")

    path = tmp_path / "spend.xlsx"
    workbook = openpyxl.Workbook()
    sheet = workbook.active
    sheet.title = "2023"
    sheet.append(["date", "merchant", "amount"])
    sheet.append(["2023-04-01", "Costco Wholesale", 142.50])
    workbook.create_sheet("2024").append(["date", "merchant", "amount"])
    workbook.save(str(path))

    result = text.extract(path)

    assert result.status == "complete"
    assert "Costco Wholesale" in result.text
    assert "142.5" in result.text
    assert "[sheet: 2023]" in result.text, "sheet names give a row its context"


def test_xlsx_sheet_becomes_its_own_page(tmp_path: Path):
    """Sheets map to pages so a citation can name which sheet a value came from."""
    openpyxl = pytest.importorskip("openpyxl")

    path = tmp_path / "multi.xlsx"
    workbook = openpyxl.Workbook()
    workbook.active.title = "First"
    workbook.active.append(["alpha"])
    second = workbook.create_sheet("Second")
    second.append(["beta"])
    workbook.save(str(path))

    result = text.extract(path)

    assert len(result.pages) == 2


def test_pdf_with_text_layer_extracts_and_pages(tmp_path: Path):
    """A real PDF with a text layer: content extracted, page provenance kept.

    Built via cupsfilter (macOS) since pypdf cannot author content streams.
    """
    pytest.importorskip("pypdf")
    import shutil
    import subprocess

    if not shutil.which("cupsfilter"):
        pytest.skip("cupsfilter unavailable; cannot author a text-layer PDF")

    source = tmp_path / "w2.txt"
    source.write_text(
        "Form W-2  Wage and Tax Statement    2023\n\n"
        "c  Employer name    ACME Corporation\n\n"
        "1  Wages, tips, other compensation    91500.00\n"
        "2  Federal income tax withheld        13725.00\n"
    )
    path = tmp_path / "w2.pdf"
    with open(path, "wb") as out:
        subprocess.run(["cupsfilter", str(source)], stdout=out,
                       stderr=subprocess.DEVNULL, check=True)

    result = text.extract(path)

    assert result.status == "complete"
    assert "91500.00" in result.text
    assert "ACME Corporation" in result.text
    assert result.pages, "page structure must survive extraction"


def test_pdf_without_text_layer_requests_ocr(tmp_path: Path):
    """A scanned PDF has no text layer; that is 'needs OCR', not 'failed'."""
    pypdf = pytest.importorskip("pypdf")

    path = tmp_path / "scan.pdf"
    writer = pypdf.PdfWriter()
    writer.add_blank_page(width=612, height=792)
    with open(path, "wb") as fh:
        writer.write(fh)

    result = text.extract(path)

    assert result.status == "partial"
    assert result.needs_ocr
    assert "OCR" in result.note


def test_pdf_without_text_is_still_findable_by_filename(conn, cfg, nas):
    """FR-2: a scanned document must not vanish from the index."""
    pypdf = pytest.importorskip("pypdf")

    path = nas / "W2_2023_scanned.pdf"
    writer = pypdf.PdfWriter()
    writer.add_blank_page(width=612, height=792)
    with open(path, "wb") as fh:
        writer.write(fh)

    Scanner(conn, cfg).scan(nas)
    Indexer(conn, cfg).run_pending()

    hits = SearchEngine(conn).search("W2_2023_scanned").hits

    assert len(hits) == 1
    assert conn.execute(
        "SELECT extraction_status FROM items"
    ).fetchone()["extraction_status"] == "partial", "pending OCR must be visible"


def test_corrupt_file_does_not_break_the_pipeline(conn, cfg, nas):
    """One bad file must not stop the rest of a scan."""
    (nas / "broken.pdf").write_bytes(b"%PDF-1.4 truncated garbage")
    (nas / "fine.txt").write_text("perfectly readable content")

    Scanner(conn, cfg).scan(nas)
    result = Indexer(conn, cfg).run_pending()

    assert result.processed == 2
    assert len(SearchEngine(conn).search("readable content").hits) == 1
